[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
  "forge-std/=lib/forge-std/src/",
  "evmate/=lib/evmate/contracts/"
]
solc_version = "0.8.17"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
